### PR TITLE
Added security features to log function for all users

### PR DESCRIPTION
**Pull request by joranvanerk**
All variables incoming within the log function will now be checked for existence. It would be nice if someone can have a look at my updated code. The latest security feature has been added.

### CODE REVIEW

**Comment by PercyFalco** [comment]
Try adding some comments in the beginning of the code. other than that it looks fine

**Comment by joranvanerk** [comment]
> Try adding some comments in the beginning of the code. other than that it looks fine

You tell me what to do?!? Nah just kidding, but thnx. What do you think about the CatchTry instead of TryCatch method? 😃

**Comment by maikel-dj** [comment]
CatchTry is absolutely stunning! But jokes aside try adding some comment for documentation purposes next time, but looks all good besides

**Comment by joranvanerk** [comment]
I'm not keeping jokes aside, jokes make me feel alive. CatchTry is something amazing!! Try implementing that into everything you can! 👍

**Comment by maikel-dj** [comment]
Just merge it already :(

**Pull request merged**
